name: ShellCraft
options:
  bundleIdPrefix: com.shahine
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "16.0"
  minimumXcodeGenVersion: "2.40"
  groupSortPosition: top
  createIntermediateGroups: true
  defaultConfig: Debug
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    ENABLE_HARDENED_RUNTIME: true
    SWIFT_STRICT_CONCURRENCY: complete
targets:
  ShellCraft:
    type: application
    platform: macOS
    sources:
      - path: ShellCraft
        excludes:
          - "**/*.xcassets/AppIcon.appiconset/Contents.json"
          - "ShellCraft.icon"
      - path: ShellCraft/ShellCraft.icon
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shahine.ShellCraft
        PRODUCT_NAME: ShellCraft
        INFOPLIST_GENERATION_MODE: GeneratedByXcode
        CODE_SIGN_ENTITLEMENTS: ShellCraft/ShellCraft.entitlements
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: N9DRSTM2U6
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: true
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        ASSETCATALOG_COMPILER_APPICON_NAME: ShellCraft
        INFOPLIST_KEY_CFBundleDisplayName: ShellCraft
    entitlements:
      path: ShellCraft/ShellCraft.entitlements
  ShellCraftTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: ShellCraftTests
    dependencies:
      - target: ShellCraft
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.shahine.ShellCraftTests
        GENERATE_INFOPLIST_FILE: true
